### ISSUE TITLE
Request for Information on Using 3D Skeleton Key Point Coordinates to Drive Skeletal Mesh Movement in UE5

### ISSUE THREAD

**Issue by KaiT-intel** [Jooh34/UE5-Mediapipe-PoseEstimation#1]
I am highly interested in your project, mentioned in the README, which utilizes Mediapipe to obtain 3D skeleton key point coordinates and drive skeletal mesh movement in UE5. Although I understand that your project is not open source, I would like to inquire about the approach to achieve this particular functionality.
If possible, I would greatly appreciate it if you could provide some guidance or suggestions on how to use 3D skeleton key point coordinates to drive skeletal mesh movement in UE5. I am enthusiastic about learning and exploring this technology, and I sincerely appreciate any help you can offer.
If you have any time or resources available to answer my questions or provide some guidance, it would be of immense value to me. However, I completely understand if there are any limitations or reasons why detailed information cannot be shared.
Thank you for your time and consideration.

**Comment by Jooh34** [comment]
Hi imjxy. Thank you for your attention.
First of all, Inferencing onnx file can be done with [OnnxRuntime-UnrealEngine](https://github.com/microsoft/OnnxRuntime-UnrealEngine)
, which is available on Windows only.
Driving to skeletal mesh animation is slightly challenging.
I cannot give you whole source code, but can share some core logic.

```
FQuat UMyAnimInstance::SolveRotator(USkeletalMeshComponent* SkelComp, FName Bone, FName ParentBone, const FVector& LandmarkPoint, const FVector& ParentLandmarkPoint, FQuat& Stack, bool bDebug)
{
	Stack = Stack * SkelComp->GetSocketTransform(ParentBone, RTS_ParentBoneSpace).Rotator().Quaternion();
	FVector TargetVector = Stack.UnrotateVector(LandmarkPoint - ParentLandmarkPoint);
	FVector StartVector = SkelComp->GetSocketTransform(Bone, RTS_ParentBoneSpace).GetTranslation();
	TargetVector.Normalize();
	StartVector.Normalize();
	FQuat Rot = FQuat::FindBetweenNormals(StartVector, TargetVector);
	Stack = Stack * Rot;
	return Rot;
} 
```

SolveRotator function calculate rotation(Stack) that make 'LandmarkPoint -> ParentLandmarkPoint' vector match 'Bone -> ParentBone' vector.
using this function, and with knowledge how character animation works in computer graphics theory,
like below source code ..

```
		FQuat LeftUpperStack = SpineStack;
		FQuat LeftCalvicleRot = SolveRotator(Fix, FName("upperarm_l"), FName("clavicle_l"), RndPC->RefinedPoseLandmarks[11], ClavicleL, LeftUpperStack);
		ClavicleLRotator = LeftCalvicleRot.Rotator();

		FQuat LeftUpperArmRot = SolveRotator(Fix, FName("lowerarm_l"), FName("upperarm_l"), RndPC->RefinedPoseLandmarks[13], RndPC->RefinedPoseLandmarks[11], LeftUpperStack);
		MediaipipePoseRotators[11] = LeftUpperArmRot.Rotator();

		FQuat LeftLowerArmRot = SolveRotator(Fix, FName("hand_l"), FName("lowerarm_l"), RndPC->RefinedPoseLandmarks[15], RndPC->RefinedPoseLandmarks[13], LeftUpperStack);
		MediaipipePoseRotators[13] = LeftLowerArmRot.Rotator();

		FQuat LeftWristRot = SolveRotator(Fix, FName("middle_01_l"), FName("hand_l"), RndPC->RefinedLeftHandLandmarks[9], RndPC->RefinedLeftHandLandmarks[0], LeftUpperStack);
		MediaipipeHandRotatorsLeft[0] = LeftWristRot.Rotator();

		FQuat LeftThumbStack = LeftUpperStack;
		FQuat LeftThumbRot = SolveRotator(Fix, FName("thumb_02_l"), FName("thumb_01_l"), RndPC->RefinedLeftHandLandmarks[2], RndPC->RefinedLeftHandLandmarks[1], LeftThumbStack);
		MediaipipeHandRotatorsLeft[1] = LeftThumbRot.Rotator();
		LeftThumbRot = SolveRotator(Fix, FName("thumb_03_l"), FName("thumb_02_l"), RndPC->RefinedLeftHandLandmarks[3], RndPC->RefinedLeftHandLandmarks[2], LeftThumbStack);
		MediaipipeHandRotatorsLeft[2] = LeftThumbRot.Rotator();
		LeftThumbRot = SolveRotator(Fix, FName("thumb_04_l"), FName("thumb_03_l"), RndPC->RefinedLeftHandLandmarks[4], RndPC->RefinedLeftHandLandmarks[3], LeftThumbStack);
		MediaipipeHandRotatorsLeft[3] = LeftThumbRot.Rotator();
```

finally, with calculated Rotator, drive animation with Unreal Animation Blueprint.
key prerequisites for this project is forward kinematics, quaternion.

I'm sorry for not sharing enough informations and I hope this helps.
thank you.

**Comment by KaiT-intel** [comment]
thanks,it is really helpful.It is very kind of you
